### ISSUE TITLE
Error Instalacion Simplificada

### ISSUE THREAD

**Issue by sebastiancorrea81** [datosgobar/portal-andino#173]
Al iniciar la instalacion simplificada, me sale esto
sebastian@sebastian:~/Descargas$ sudo python ./install.py \
>     --error_email "$EMAIL" \
>     --site_host="$HOST" \
>     --database_user="$DB_USER" \
>     --database_password="$DB_PASS" \
>     --datastore_user="$STORE_USER" \
>     --datastore_password="$STORE_PASS"
[sudo] contraseña para sebastian: 
[ INFO ] Comprobando permisos (sudo)
[ INFO ] Comprobando instalación previa
[ INFO ] Comprobando que docker esté instalado...
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[ INFO ] Comprobando que docker-compose esté instalado...
docker-compose version 1.18.0, build 8dd22a9
[ INFO ] Descargando archivos necesarios...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1560  100  1560    0     0   3223      0 --:--:-- --:--:-- --:--:--  3216
[ INFO ] Escribiendo archivo de configuración del ambiente (.env) ...
[ INFO ] Configurando versión estable de andino.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     35      0 --:--:-- --:--:-- --:--:--    35
[ INFO ] Usando versión 'release-2.5.1' de andino
[ INFO ] Obteniendo imágenes de Docker
Pulling postfix (catatnight/postfix:latest)...
latest: Pulling from catatnight/postfix
a3ed95caeb02: Already exists
bb92073c7a94: Already exists
255c0b817d4e: Already exists
b5111d9274a4: Already exists
2b5c23db3bbc: Already exists
1fb9bd8e91f3: Already exists
1775fca35fb6: Already exists
704b646b3521: Already exists
7a69bc1c1265: Already exists
2688108bfd48: Already exists
Digest: sha256:11684ea62492d31bd65d4f184c6cc02519d00b4b571ea1df8e363ac5e4ee028c
Status: Image is up to date for catatnight/postfix:latest
Pulling redis (redis:3.2.7-alpine)...
3.2.7-alpine: Pulling from library/redis
Digest: sha256:95f0c9434f37db0a4f9563379184ff4895685d2381e2d81bd10dfcbcadfc095f
Status: Image is up to date for redis:3.2.7-alpine
Pulling db (postgres:9.5)...
9.5: Pulling from library/postgres
Digest: sha256:51cccaa992759b17514ab04f1be9620aaa4817845e42ce16fff194223c7670d4
Status: Image is up to date for postgres:9.5
Pulling solr (datosgobar/portal-base-solr:release-0.9.0)...
release-0.9.0: Pulling from datosgobar/portal-base-solr
Digest: sha256:597268583c6ecd031fdb0985825fe963b1fff4b8fef6b872dd85c3a56cd3138c
Status: Image is up to date for datosgobar/portal-base-solr:release-0.9.0
Pulling portal (datosgobar/portal-andino:release-2.5.1)...
release-2.5.1: Pulling from datosgobar/portal-andino
Digest: sha256:8278955ff035daa09f41f0198fffc4c581a62ae9edcda74044488ee1fb3a6f74
Status: Image is up to date for datosgobar/portal-andino:release-2.5.1
Pulling nginx (datosgobar/portal-base-nginx:release-0.10.2)...
release-0.10.2: Pulling from datosgobar/portal-base-nginx
Digest: sha256:7c5a4c9a49bdf3b12019db7dfa4d0d445d1068757523bfbb1774b65f2a1517a2
Status: Image is up to date for datosgobar/portal-base-nginx:release-0.10.2
Creating andino-db ... done
Creating andino ... done
Creating andino-nginx ... done
Creating andino-postfix ... 
Creating andino-db ... 
Creating andino-redis ... 
Creating andino ... 
Creating andino-nginx ... 
[ INFO ] Esperando a que la base de datos este disponible...
[ INFO ] Configurando...
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 ckan      | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(4 rows)

Postgres is up - executing command
ERROR:  role "postgres" already exists
CREATE DATABASE
Edited option ckan.datapusher.url = "http://localhost:8800"->"http://0.0.0.0:8800" (section "app:main")
Edited option email_to = ""->"admin@example.com" (section "app:main")
Edited option ckan.site_url = ""->"http://192.168.130.63" (section "app:main")
Edited option sqlalchemy.url = ""->"postgresql://postgres:@db:5432/ckan" (section "app:main")
Edited option ckan.datastore.write_url = ""->"postgresql://postgres:@db:5432/datastore_default" (section "app:main")
Edited option ckan.datastore.read_url = ""->"postgresql://postgres:12345678@db:5432/datastore_default" (section "app:main")
Edited option beaker.session.secret = ""->"7tIoUE2YlgJkzrmoWuJ8mdtCbMhZho/0Xg==" (section "app:main")
/usr/lib/ckan/default/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
2018-09-27 09:21:07,392 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2018-09-27 09:21:07,410 DEBUG [ckanext.harvest.model] Harvest table creation deferred
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 333, in command
    self._load_config(cmd!='upgrade')
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 306, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 221, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 167, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 271, in update_config
    plugin.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 80, in configure
    self.backend.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1696, in configure
    self._check_urls_and_permissions()
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1584, in _check_urls_and_permissions
    self._log_or_raise('The read-only user has write privileges.')
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1565, in _log_or_raise
    raise DatastoreException(message)
ckanext.datastore.backend.DatastoreException: The read-only user has write privileges.
/usr/lib/ckan/default/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
2018-09-27 09:21:09,335 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2018-09-27 09:21:09,336 DEBUG [ckanext.harvest.model] Harvest table creation deferred
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 140, in invoke
    runner = command(command_name)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 266, in __call__
    obj={})
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/commands.py", line 29, in set_permissions
    load_config(config or ctx.obj['config'])
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 221, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 167, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 271, in update_config
    plugin.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 80, in configure
    self.backend.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1696, in configure
    self._check_urls_and_permissions()
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1584, in _check_urls_and_permissions
    self._log_or_raise('The read-only user has write privileges.')
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1565, in _log_or_raise
    raise DatastoreException(message)
ckanext.datastore.backend.DatastoreException: The read-only user has write privileges.
/usr/lib/ckan/default/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
2018-09-27 09:21:11,380 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2018-09-27 09:21:11,382 DEBUG [ckanext.harvest.model] Harvest table creation deferred
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 139, in command
    self._load_config()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 212, in _load_config
    super(Harvester, self)._load_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 306, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 221, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 167, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 271, in update_config
    plugin.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 80, in configure
    self.backend.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1696, in configure
    self._check_urls_and_permissions()
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1584, in _check_urls_and_permissions
    self._log_or_raise('The read-only user has write privileges.')
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1565, in _log_or_raise
    raise DatastoreException(message)
ckanext.datastore.backend.DatastoreException: The read-only user has write privileges.
/usr/lib/ckan/default/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
2018-09-27 09:21:13,193 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2018-09-27 09:21:13,194 DEBUG [ckanext.harvest.model] Harvest table creation deferred
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-gobar-theme/ckanext/gobar_theme/lib/cli.py", line 13, in command
    self._load_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 306, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 221, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 99, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 167, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 271, in update_config
    plugin.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 80, in configure
    self.backend.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1696, in configure
    self._check_urls_and_permissions()
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1584, in _check_urls_and_permissions
    self._log_or_raise('The read-only user has write privileges.')
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1565, in _log_or_raise
    raise DatastoreException(message)
ckanext.datastore.backend.DatastoreException: The read-only user has write privileges.
Traceback (most recent call last):
  File "./install.py", line 248, in <module>
    install_andino(args, compose_url, stable_version_url)
  File "./install.py", line 206, in install_andino
    configure_application(compose_file_path, cfg)
  File "./install.py", line 153, in configure_application
    "-D", cfg.datastore_password,
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', '-f', '/etc/portal/latest.yml', 'exec', '-T', 'portal', '/etc/ckan_init.d/init.sh', '-e', 'admin@example.com', '-h', '192.168.130.63', '-p', 'postgres', '-P', '', '-d', 'postgres', '-D', '12345678']' returned non-zero exit status 1

**Comment by poligarcia** [comment]
Hola Sebastián! El error dice `DatastoreException: The read-only user has write privileges`. Por una cuestión de seguridad CKAN no permite que el usuario del datastore tenga permisos de escritura sobre la base de datos. Seguramente el usuario que le pasaste en el parámetro `STORE_USER` existe en la base de datos y tiene permisos de escritura.

Debés pasarle el nombre de un usuario que no exista (ej: `my_datastore_user`) y andino se encargará de crearlo y asignarle la contraseña que le enviaste.

**Comment by sebastiancorrea81** [comment]
Asi lo hice y funciono perfecto. Muchas Gracias
