### ISSUE TITLE
Error en la instalación simplificada

### ISSUE THREAD

**Issue by avilaton** [datosgobar/portal-andino#43]
Buenas,
intenté correr la instalación simplificada de portal andino siguiendo las instrucciones de readthedocs y choqué contra esto:
```
python ./install.py --error_email "$EMAIL" --site_host="$HOST" \
    --database_user="$DB_USER" --database_password="$DB_PASS" \
    --datastore_user="$STORE_USER" --datastore_password="$STORE_PASS"
[ INFO ] Comprobando que docker esté instalado...
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[ INFO ] Comprobando que docker-compose este instalado...
docker-compose version: 1.3.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
[ INFO ] Descargando archivos necesarios...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1270  100  1270    0     0    546      0  0:00:02  0:00:02 --:--:--   546
[ INFO ] Escribiendo archivo de configuración del ambiente (.env) ...
[ INFO ] Iniciando la aplicación
Unsupported config option for services service: 'nginx'
Traceback (most recent call last):
  File "./install.py", line 97, in <module>
    init_application(compose_file_path)
  File "./install.py", line 65, in init_application
    "nginx",
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', '-f', '/home/gavila/tonTrabajo/open-data/andino/latest.yml', 'up', '-d', 'nginx']' returned non-zero exit status 1
```
Creo el ticket para referencia y verlo luego, si se me ocurre un fix aviso.
Saludos

**Comment by poligarcia** [comment]
Hola @avilaton ! En qué plataforma estás corriendo la instlaación?

**Comment by lalo73** [comment]
Quizás la versión de `docker-compose` (version: 1.3.1) es muy vieja. ¿Podrías probar actualizándola?
La instalación está testeada con `1.13`

**Comment by avilaton** [comment]
en eso estoy, aviso cuando termine, gracias por el soporte!

**Comment by avilaton** [comment]
Así es, debe haber una versión mínima de docker-compose. Actualizarla quitó el error. Si supiera cual es la version mínima enviaría un PR para añadirlo a la documentación.
Gracias!
