### ISSUE TITLE
Error al agregar un usuario con "ñ"

### ISSUE THREAD

**Issue by andreshans** [datosgobar/portal-andino#65]
Estimados, agregamos un usuario que en su segundo nombre llevaba una ñ, Luego de eso dejo de funcionar el user list desde la consola. pero se ve desde la web

root@eec2a83c5f20:/portal# /etc/ckan_init.d/paster.sh --plugin=ckan user list
2017-09-19 19:03:52,425 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2017-09-19 19:03:52,428 DEBUG [ckanext.harvest.model] Harvest tables already exist
Users:
count = 9
name=xxxxx display=Manuel Ayr
name=xxxxx display=Blanca de la Fare
name=xxxxx display=Juan Pablo Budrovich
name=xxxxx
name=xxxxx display=Federico Scuka
name=xxxxx display=Horacio Alejandro da Costa
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 762, in command
    self.list()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 778, in list
    print self.get_user_str(user)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 48: ordinal not in range(128)
root@eec2a83c5f20:/portal# 

![screenshot from 2017-09-20 12-08-49](https://user-images.githubusercontent.com/236838/30651575-84e0ad3c-9dfc-11e7-8161-84020d076c9f.png)

**Comment by iheredia** [comment]
Hola @andreshans 
Gracias por reportar el bug

Recién chequeé el bug y lo pude reproducir. 
Como forma rápida para que puedas correr el comando, podes setear la variable `PYTHONIOENCODING` y correr 
`PYTHONIOENCODING=utf-8 /etc/ckan_init.d/paster.sh --plugin=ckan user list ` 

Independientemente, voy a editar el archivo `paster.sh` para que ya incorpore esta variable en todos los llamados. Una vez editado, voy a sacar una nueva version del portal (la version 2.2.5) para que puedan actualizar el portal y dejen de tener este issue.

Saludos
